#!/bin/bash

### ffmpeg -framerate 30 image1.jpg image2.jpg -i '*.png' -c:v libx264 -pix_fmt yuv420p out.mp4
### ffmpeg -loop 1 -i image1.jpg -c:v libx264 -t 15 -pix_fmt yuv420p -vf scale=320:240 out.mp4

# ffmpeg -framerate 30 -pattern_type glob -i '*.jpg' -c:v libx264 -r 10 -pix_fmt yuv420p out.mp4

# ffmpeg -framerate 30 -i 'workdir/%04d.png' -c:v libx264 -r 10 -pix_fmt yuv420p out2.mp4

# ffmpeg -i out2.mp4 -i try2.wav -c:v copy -c:a aac out3.mp4

ffmpeg -framerate 30 -start_number 55 -i 'workdir/%04d.png' -i try2.wav -c:v libx264 -c:a aac -r 10 -pix_fmt yuv420p out2a.mp4
