#!/bin/bash

### ffmpeg -framerate 30 image1.jpg image2.jpg -i '*.png' -c:v libx264 -pix_fmt yuv420p out.mp4
### ffmpeg -loop 1 -i image1.jpg -c:v libx264 -t 15 -pix_fmt yuv420p -vf scale=320:240 out.mp4

# ffmpeg -framerate 30 -pattern_type glob -i '*.jpg' -c:v libx264 -r 10 -pix_fmt yuv420p out.mp4

function mk_montage() {
    montage -density 300 -tile 4x3 -geometry +5+50 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $2
}


mk_montage image1.jpg image12a.jpg
mk_montage image2.jpg image12b.jpg

ffmpeg -framerate 30 -pattern_type glob -i 'image12*.jpg' -c:v libx264 -r 10 -pix_fmt yuv420p out.mp4
